// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARHpJQdSiZboEyRgRcOwRqtG8GGp8AxAo',
    appId: '1:1015315168321:web:850ad55f2eb182c90d5ac0',
    messagingSenderId: '1015315168321',
    projectId: 'projeto-agenda-2024',
    authDomain: 'projeto-agenda-2024.firebaseapp.com',
    storageBucket: 'projeto-agenda-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBarygXOYXRNdvc7VWJb4FQ_AW3R4-5m08',
    appId: '1:1015315168321:android:622fad6e73598b7d0d5ac0',
    messagingSenderId: '1015315168321',
    projectId: 'projeto-agenda-2024',
    storageBucket: 'projeto-agenda-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYcWfPjEJuVVd6ZuWgJsBYwi7lR5NbGOo',
    appId: '1:1015315168321:ios:d164d2308b3267390d5ac0',
    messagingSenderId: '1015315168321',
    projectId: 'projeto-agenda-2024',
    storageBucket: 'projeto-agenda-2024.appspot.com',
    iosBundleId: 'com.example.primeiro2024',
  );
}
